apiVersion: v1
kind: Namespace
metadata:
  name: adventofcode
---
apiVersion: v1
kind: Service
metadata:
  name: rstore
  namespace: rstore
  labels:
    app: rstore
spec:
  type: NodePort
  metadata:
    labels:
      app: rstore
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: rstore
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rstore
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - rstore
  selector:
    matchLabels:
      app: rstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstore
  namespace: rstore
spec:
  selector:
    matchLabels:
      app: rstore
  replicas: 1
  template:
    metadata:
      labels:
        app: rstore
    spec:
      nodeName: klust2
      containers:
        - name: restore
          image: registry.brotherlogic-backend.com/brotherlogic/rstore:0.60.0 # {"$imagepolicy": "flux-system:rstore"}
          ports:
            - containerPort: 8080
          args: ["--mongo=$(CONNECTION_STRING)"]
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-madmin
                  namespace: mongo
                  key: connectionString.standardSrv
      imagePullSecrets:
        - name: regcred
